postgres:
    image: postgres:9.4
    ports:
        - "5432:5432"
    volumes:
        - /data/prestapi.:/var/lib/postgresql/data

prestapi:
    build: .
    command: /src/dist/build/prestapi/prestapi production --port 3000
    links:
        - postgres
    volumes:
        - ./src:/src
    environment:
        PGHOST: "192.168.99.100"
        PGUSER: "postgres"
        PGPASS: ""
    ports:
        - "3000:3000"
